treatments:
  - name: hard_noFeedback
    factorIds:
      - LCPL67GcDLnC7kpX4
      - zAoBH7r4FvddSqPJc
      - PhWBYRyqGv7hpZbKm
      - 87LioersRD2W7zkNd
      - pb9pfqeJBqCHrRX2X
      - KkEgf4EFFKNNk9Pbe
factorTypes:
  - _id: qvL8y4mSRvgiFqoC8
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: kJddTH8X4Y6Df7SPA
    name: selectionDuration
    description: >-
      how many seconds do participants have to complete a tangram selection
      trial
    required: true
    type: String
  - _id: oTmtc6KmQb77CaDTC
    name: submitCode
    description: code for submission to prolific/mturk
    required: false
    type: String
  - _id: KWbBqHzyqqgrELxi2
    name: numRepetitionsWithPartner
    description: 'how many times does each tangram repeat as the target (i.e. # blocks)'
    required: false
    type: Integer
    min: 1
    max: 10
  - _id: gFhhDqetCocmAwtMX
    name: contextSize
    description: how big is the context?
    required: true
    type: Integer
    min: 2
    max: 12
  - _id: ECiwfo8x4o9xrCopQ
    name: showNegativeFeedback
    description: >-
      If `true`, will show the listener the correct target (and show the speaker
      the listener's selection) when they make an error. If `false` only binary
      feedback will be shown.
    required: true
    type: Boolean
factors:
  - _id: meEAFnxMm952XrPmY
    name: 'true'
    value: true
    factorTypeId: ECiwfo8x4o9xrCopQ
  - _id: KkEgf4EFFKNNk9Pbe
    name: 'false'
    value: false
    factorTypeId: ECiwfo8x4o9xrCopQ
  - _id: LCPL67GcDLnC7kpX4
    name: duo
    value: 2
    factorTypeId: qvL8y4mSRvgiFqoC8
  - _id: PhWBYRyqGv7hpZbKm
    name: prolificPilot
    value: 3B021164
    factorTypeId: oTmtc6KmQb77CaDTC
  - _id: zAoBH7r4FvddSqPJc
    name: '45'
    value: '45'
    factorTypeId: kJddTH8X4Y6Df7SPA
  - _id: 87LioersRD2W7zkNd
    name: five
    value: 5
    factorTypeId: KWbBqHzyqqgrELxi2
  - _id: pb9pfqeJBqCHrRX2X
    name: full
    value: 12
    factorTypeId: gFhhDqetCocmAwtMX
  - _id: YMLq8iWJv6FnspX6P
    name: half
    value: 6
    factorTypeId: gFhhDqetCocmAwtMX
  - _id: P6EqZwPGGp8aPhN3g
    name: easy
    value: 4
    factorTypeId: gFhhDqetCocmAwtMX
lobbyConfigs:
  - name: lobby
    timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
    archivedAt: 2021-01-20T10:15:45.633Z
  - name: individual_lobby
    timeoutType: individual
    timeoutInSeconds: 300
    timeoutStrategy: fail
    extendCount: 2
    gameLobbyIds: []
